#!/bin/bash

while test -n "$1"; do
    set=1
    case "$1" in
        -w)
            warning=$2
            shift
            ;;
        -c)
            critical=$2
            shift
            ;;
        -f)
            field=$2
            shift
            ;;
        *)
            echo "Unknown argument: $1"
            exit 3
            ;;
        esac
    shift
done

STATUS="OK"
DEV_STATE=
iostat -tx | grep "sd." > /tmp/iostat-info
col_number=`iostat -tx | awk -v field=$field '{ for (i=1; i<=NF; i++) { if ( $i == field) print i } }'`
count=`cat /tmp/iostat-info | wc -l`
for (( i=1; i<=$count; i++ ));
do
   row=`cat /tmp/iostat-info | awk -v i=$i 'NR == i'`
   field_value=`echo $row | awk -v col_number=$col_number '{ print $col_number }' | sed 's/,/./g'`
   device=`echo $row | awk '{ print $1 }'`
   if [ $(echo "$field_value<$warning" | bc) -eq "1" ]
   then
       DEV_STATE=$DEV_STATE"Status of $device: OK, $field $field_value; \t"
   elif [ $(echo "$field_value<$warning" | bc) -eq "1" ]
   then
       DEV_STATE=$DEV_STATE"Status of $device: WARNING, $field $field_value; \t"
       STATUS="WARNING"
   else
       DEV_STATE=$DEV_STATE"Status of $device: CRITICAL, $field $field_value; \t"
       STATUS="CRITICAL"
   fi
done

if [ -z "$DEV_STATE" ]
then
   echo "Not found any hard device: $devices"
   exit 3
fi
if [ $STATUS == "OK" ]
then
   echo -e $DEV_STATE
   exit 0
elif [ $STATUS == "WARNING" ]
then
   echo -e $DEV_STATE
   exit 1
else
   echo -e $DEV_STATE
   exit 2
fi
